
package view;

import controller.LoginAction;
import data.AdminReport;
import data.Defines;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import model.Model;

/**
 * The Report Page
 * @author Cosmin Elvis Anita
 */
public class AdminJDialog extends javax.swing.JDialog implements PropertyChangeListener{
    Model           model;
    LoginAction     loginAction;
    
    /**
     * Creates new form AdminJDialog, 
     * @param parent
     * @param modal
     * @param model
     */
    public AdminJDialog(java.awt.Frame parent, boolean modal,Model model) {
        super(parent, modal);
       
        initComponents();
        
        this.model = model;
        model.addPropertyChangeListener(this);
        
        loginAction = new LoginAction(model);
        jButton1.addActionListener(loginAction);
        
        jLabel4.setVisible(false);
        jLabel5.setVisible(false);
        jLabel6.setVisible(false);
        jLabel7.setVisible(false);
        jLabel8.setVisible(false);
        jLabel9.setVisible(false);

        jTextField1.addKeyListener(
            new KeyAdapter() {
                @Override
                public void keyReleased(KeyEvent e) {
                    loginAction.setUser(((JTextField)e.getSource()).getText());
                }
            }
        );
        
        jPasswordField1.addKeyListener(
            new KeyAdapter() {
                @Override
                public void keyReleased(KeyEvent e) {
                    loginAction.setPass(((JPasswordField)e.getSource()).getText());
                }
            }
        );

    }

    /**
     *Resets the report page to look like a login page
     */
    public void resetToLogin(){
        jLabel1.setVisible(true);
        jLabel2.setVisible(true);
        jButton1.setVisible(true);
        jTextField1.setVisible(true);
        jTextField1.setText("");
        jPasswordField1.setVisible(true);
        jPasswordField1.setText("");
        loginAction.setUser("");
        loginAction.setPass("");

        jLabel4.setVisible(false);
        jLabel5.setVisible(false);
        jLabel6.setVisible(false);
        jLabel7.setVisible(false);
        jLabel8.setVisible(false);
        jLabel9.setVisible(false);

        repaint();
    }
    
    /**
     * Catches property change event
     * @param pce
     */
    @Override
    public void propertyChange(PropertyChangeEvent pce) {
        switch (pce.getPropertyName()) {
            case Defines.EVENT_LOGGED:
                AdminReport adminReport;
                adminReport = (AdminReport)pce.getNewValue();
                
                jLabel6.setText("£ " + adminReport.dProfit.toString());
                jLabel4.setText("£ " + adminReport.dLosses.toString());
                jLabel5.setText("£ " + adminReport.dTotalMoney.toString());
                
                jLabel1.setVisible(false);
                jLabel2.setVisible(false);
                jButton1.setVisible(false);
                jTextField1.setVisible(false);
                jPasswordField1.setVisible(false);
                
                jLabel4.setVisible(true);
                jLabel5.setVisible(true);
                jLabel6.setVisible(true);
                jLabel7.setVisible(true);
                jLabel8.setVisible(true);
                jLabel9.setVisible(true);
                
                repaint();
                
                break;
            default: 
                break;
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(0, 153, 51));
        setMaximumSize(new java.awt.Dimension(400, 300));
        setMinimumSize(new java.awt.Dimension(400, 300));
        setModal(true);
        setResizable(false);
        setSize(new java.awt.Dimension(400, 300));

        jPanel1.setBackground(new java.awt.Color(0, 153, 51));
        jPanel1.setMaximumSize(new java.awt.Dimension(400, 300));
        jPanel1.setMinimumSize(new java.awt.Dimension(400, 300));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel1.setText("Password:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 150, 80, 40);

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel2.setText("User:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 80, 80, 40);

        jPasswordField1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jPasswordField1.setText("jPasswordField1");
        jPasswordField1.setToolTipText("Enter Password");
        jPanel1.add(jPasswordField1);
        jPasswordField1.setBounds(100, 150, 290, 40);

        jTextField1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jTextField1.setToolTipText("Enter Username");
        jPanel1.add(jTextField1);
        jTextField1.setBounds(100, 80, 290, 40);

        jButton1.setBackground(new java.awt.Color(0, 153, 51));
        jButton1.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jButton1.setText("Login");
        jButton1.setToolTipText("Press to Login");
        jPanel1.add(jButton1);
        jButton1.setBounds(293, 210, 100, 40);

        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(150, 40, 100, 30);

        jLabel5.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(270, 40, 100, 30);

        jLabel6.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jPanel1.add(jLabel6);
        jLabel6.setBounds(30, 40, 100, 30);

        jLabel7.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jLabel7.setText("Losses");
        jLabel7.setToolTipText("Current Losses");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(150, 10, 100, 30);

        jLabel8.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jLabel8.setText("Total");
        jLabel8.setToolTipText("Total Amount of Coins");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(270, 10, 100, 30);

        jLabel9.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jLabel9.setText("Profit");
        jLabel9.setToolTipText("Total Profit");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(30, 10, 100, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
