package view;


import controller.CashInAction;
import controller.CokeSelectionAction;
import controller.CrispsSelectionAction;
import controller.EugeniaSelectionAction;
import controller.InsertCoinAction;
import controller.MarsSelectionAction;
import controller.PayForSnackAction;
import controller.WaterSelectionAction;
import data.Defines;
import data.ECoinTypes;
import data.ESnackTypes;
import data.SyncUpData;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import model.Model;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 * The Main View
 * @author Cosmin Elvis Anita
 */
public class MainJFrame extends javax.swing.JFrame implements PropertyChangeListener{

    Model                   model;
    InsertCoinAction        insertedCoinAction;
    PayForSnackAction       payForSnackAction;
    CashInAction            cashInAction;
    CrispsSelectionAction   crispsSelectionAction;
    MarsSelectionAction     marsSelectionAction;
    CokeSelectionAction     cokeSelectionAction;
    EugeniaSelectionAction  eugeniaSelectionAction;
    WaterSelectionAction    waterSelectionAction;
    AdminJDialog            adminJDialog;
    
    /**
     * Creates new form MainJFrame, instantiates
     * and initializes all members
     */
    public MainJFrame() {
        initComponents();
        
        model = new Model();
        model.initialize();
        model.addPropertyChangeListener(this);
        
        insertedCoinAction = new InsertCoinAction(model);
        insertedCoinAction.setCoinType(ECoinTypes.E_0_05);
        jButton1.addActionListener(insertedCoinAction);
        
        payForSnackAction = new PayForSnackAction(model);
        payForSnackAction.setSelectedQuantity(1);
        jButton3.addActionListener(payForSnackAction);
        
        cashInAction = new CashInAction(model); 
        jButton4.addActionListener(cashInAction);

        cashInAction = new CashInAction(model); 
        jButton4.addActionListener(cashInAction);
        
        crispsSelectionAction = new CrispsSelectionAction(model);
        jToggleButton1.addActionListener(crispsSelectionAction);
        
        marsSelectionAction = new MarsSelectionAction(model);
        jToggleButton2.addActionListener(marsSelectionAction);
        
        cokeSelectionAction = new CokeSelectionAction(model);
        jToggleButton3.addActionListener(cokeSelectionAction);
        
        eugeniaSelectionAction = new EugeniaSelectionAction(model);
        jToggleButton4.addActionListener(eugeniaSelectionAction);
        
        waterSelectionAction = new WaterSelectionAction(model);
        jToggleButton5.addActionListener(waterSelectionAction);
        
        jSlider2.setMaximum(-1);
        
        ShowSnackMachineInFront(false);
        
        setButton1BadgeState(false);
        setButton2BadgeState(false);
        setButton3BadgeState(false);
        setButton4BadgeState(false);
        setButton5BadgeState(false);
        
        adminJDialog = new view.AdminJDialog(this, true, model);
        adminJDialog.resetToLogin();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        jToggleButton4 = new javax.swing.JToggleButton();
        jToggleButton5 = new javax.swing.JToggleButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSlider1 = new javax.swing.JSlider();
        jButton1 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSlider2 = new javax.swing.JSlider();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(800, 600));

        jPanel1.setLayout(null);

        jToggleButton1.setBackground(new java.awt.Color(255, 255, 255));
        jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/crisps.jpg"))); // NOI18N
        jToggleButton1.setToolTipText("Select Crisps");
        jToggleButton1.setBorder(null);
        jToggleButton1.setBorderPainted(false);
        jToggleButton1.setName("btn_crisps"); // NOI18N
        jToggleButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/crisps_hover.jpg"))); // NOI18N
        jToggleButton1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/crisps_selected.jpg"))); // NOI18N
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton1);
        jToggleButton1.setBounds(78, 10, 100, 100);

        jToggleButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/marsBar.jpg"))); // NOI18N
        jToggleButton2.setToolTipText("Select Mars Bar");
        jToggleButton2.setName("btn_mars"); // NOI18N
        jToggleButton2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/marsBar_hover.jpg"))); // NOI18N
        jToggleButton2.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/marsBar_selected.jpg"))); // NOI18N
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton2);
        jToggleButton2.setBounds(20, 120, 100, 100);

        jToggleButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/cocaCola.jpg"))); // NOI18N
        jToggleButton3.setToolTipText("Select Coca Cola");
        jToggleButton3.setName("btn_coke"); // NOI18N
        jToggleButton3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/cocaCola_hover.jpg"))); // NOI18N
        jToggleButton3.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/cocaCola_selected.jpg"))); // NOI18N
        jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton3);
        jToggleButton3.setBounds(80, 230, 100, 100);

        jToggleButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/eugenia.jpg"))); // NOI18N
        jToggleButton4.setToolTipText("Select Eugenia");
        jToggleButton4.setName("btn_eugenia"); // NOI18N
        jToggleButton4.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/eugenia_hover.jpg"))); // NOI18N
        jToggleButton4.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/eugenia_selected.jpg"))); // NOI18N
        jToggleButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton4);
        jToggleButton4.setBounds(20, 340, 100, 100);

        jToggleButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/water.jpg"))); // NOI18N
        jToggleButton5.setToolTipText("Select Bottle of Water");
        jToggleButton5.setName("btn_water"); // NOI18N
        jToggleButton5.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/water_hover.jpg"))); // NOI18N
        jToggleButton5.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/water_selected.jpg"))); // NOI18N
        jToggleButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton5);
        jToggleButton5.setBounds(80, 450, 100, 100);

        jLabel10.setFont(new java.awt.Font("Arial Narrow", 1, 16)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("10");
        jLabel10.setToolTipText("Quantity");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(180, 22, 25, 25);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/badge_open.png"))); // NOI18N
        jLabel5.setLabelFor(jLabel10);
        jPanel1.add(jLabel5);
        jLabel5.setBounds(178, 22, 25, 25);

        jLabel11.setFont(new java.awt.Font("Arial Narrow", 1, 16)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setText("10");
        jLabel11.setToolTipText("Quantity");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(122, 132, 25, 25);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/badge_open.png"))); // NOI18N
        jLabel6.setLabelFor(jLabel4);
        jPanel1.add(jLabel6);
        jLabel6.setBounds(120, 132, 25, 25);

        jLabel12.setFont(new java.awt.Font("Arial Narrow", 1, 16)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel12.setText("10");
        jLabel12.setToolTipText("Quantity");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(182, 242, 25, 25);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/badge_open.png"))); // NOI18N
        jLabel7.setLabelFor(jLabel4);
        jPanel1.add(jLabel7);
        jLabel7.setBounds(180, 242, 25, 25);

        jLabel13.setFont(new java.awt.Font("Arial Narrow", 1, 16)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel13.setText("10");
        jLabel13.setToolTipText("Quantity");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(122, 352, 25, 25);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/badge_open.png"))); // NOI18N
        jLabel8.setLabelFor(jLabel4);
        jPanel1.add(jLabel8);
        jLabel8.setBounds(120, 352, 25, 25);

        jLabel14.setFont(new java.awt.Font("Arial Narrow", 1, 16)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel14.setText("10");
        jLabel14.setToolTipText("Bottle of Water Quantity");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(182, 462, 25, 25);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/badge_open.png"))); // NOI18N
        jLabel9.setLabelFor(jLabel4);
        jPanel1.add(jLabel9);
        jLabel9.setBounds(180, 462, 25, 25);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/coin_0.05.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.setToolTipText("Coin Denomination");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(700, 20, 55, 75);

        jSlider1.setBackground(new java.awt.Color(0, 0, 0));
        jSlider1.setMaximum(4);
        jSlider1.setOrientation(javax.swing.JSlider.VERTICAL);
        jSlider1.setToolTipText("Select Denomination");
        jSlider1.setValue(0);
        jSlider1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider1StateChanged(evt);
            }
        });
        jPanel1.add(jSlider1);
        jSlider1.setBounds(760, 20, 30, 120);

        jButton1.setBackground(new java.awt.Color(0, 153, 51));
        jButton1.setFont(new java.awt.Font("Arial Narrow", 1, 11)); // NOI18N
        jButton1.setText("Insert");
        jButton1.setToolTipText("Insert Coin");
        jPanel1.add(jButton1);
        jButton1.setBounds(700, 100, 59, 40);

        jLabel18.setFont(new java.awt.Font("Arial Narrow", 1, 24)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("1 pc");
        jLabel18.setToolTipText("Snack Quantity");
        jLabel18.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(jLabel18);
        jLabel18.setBounds(450, 420, 220, 30);

        jLabel19.setFont(new java.awt.Font("Arial Narrow", 1, 48)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("£0");
        jLabel19.setToolTipText("Price");
        jLabel19.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel19);
        jLabel19.setBounds(450, 360, 220, 40);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/crisps_big.jpg"))); // NOI18N
        jLabel3.setToolTipText("");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(450, 124, 220, 220);

        jSlider2.setMaximum(9);
        jSlider2.setToolTipText("Select Quantity");
        jSlider2.setValue(0);
        jSlider2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider2StateChanged(evt);
            }
        });
        jPanel1.add(jSlider2);
        jSlider2.setBounds(460, 380, 200, 60);

        jLabel15.setFont(new java.awt.Font("Arial Narrow", 1, 28)); // NOI18N
        jLabel15.setText("0.00");
        jLabel15.setToolTipText("Your Change");
        jLabel15.setName("lbl_cash_in"); // NOI18N
        jPanel1.add(jLabel15);
        jLabel15.setBounds(470, 500, 200, 30);

        jLabel16.setFont(new java.awt.Font("Arial Narrow", 1, 36)); // NOI18N
        jLabel16.setText("0.00");
        jLabel16.setToolTipText("Inserted Coins");
        jLabel16.setName("lbl_coins_inserted"); // NOI18N
        jPanel1.add(jLabel16);
        jLabel16.setBounds(470, 30, 200, 50);

        jButton3.setBackground(new java.awt.Color(0, 153, 51));
        jButton3.setFont(new java.awt.Font("Arial Narrow", 1, 11)); // NOI18N
        jButton3.setText("Pay");
        jButton3.setToolTipText("Pay for Snacks");
        jPanel1.add(jButton3);
        jButton3.setBounds(700, 150, 80, 50);

        jButton4.setBackground(new java.awt.Color(0, 153, 51));
        jButton4.setFont(new java.awt.Font("Arial Narrow", 1, 11)); // NOI18N
        jButton4.setText("Cash In");
        jButton4.setToolTipText("Take Your Change");
        jPanel1.add(jButton4);
        jButton4.setBounds(700, 490, 80, 50);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/balance.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(400, 2, 393, 566);

        jLabel17.setFont(new java.awt.Font("Arial Narrow", 1, 24)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("<html><h1>******* 10,000 Steps Healthy Snacks *******</h1></html>");
        jLabel17.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel17);
        jLabel17.setBounds(360, 160, 440, 70);

        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("<html><h2> &lt;-  Choose Your Snack To Continue</h2></html>");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(360, 230, 430, 80);

        jLabel21.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        jLabel21.setText("<html><a href=\"url\">Sign In</a></html>");
        jLabel21.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel21MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel21);
        jLabel21.setBounds(740, 570, 50, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/background.png"))); // NOI18N
        jLabel1.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 800, 600);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

     /**
     * Selects Crisps snack, sets up the state of the main view
     * and sets the coin type for some controllers.
     * @param evt
     */
    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        boolean bValue = jToggleButton1.isSelected();
        
        setButton1BadgeState(bValue);
        
        if (true == bValue){
            ImageIcon icon = new ImageIcon(getClass().getResource(Defines.RESOURCES_PATH + "crisps_big.jpg"));
            jLabel3.setIcon(icon);
            
            setButton2BadgeState(!bValue);
            setButton3BadgeState(!bValue);
            setButton4BadgeState(!bValue);
            setButton5BadgeState(!bValue);
            
            payForSnackAction.setSnackType(ESnackTypes.E_CRISPS);
            insertedCoinAction.setSnackType(ESnackTypes.E_CRISPS);
            jSlider2.setValue(0);
        }
        
        ShowSnackMachineInFront(bValue);
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    /**
     * Selects Mars Bar snack, sets up the state of the main view
     * and sets the coin type for some controllers.
     * @param evt
     */
    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        boolean bValue = jToggleButton2.isSelected();
        
        setButton2BadgeState(bValue);
        
        if (true == bValue){
            ImageIcon icon = new ImageIcon(getClass().getResource(Defines.RESOURCES_PATH + "marsBar_big.jpg"));
            jLabel3.setIcon(icon);
            
            setButton1BadgeState(!bValue);
            setButton3BadgeState(!bValue);
            setButton4BadgeState(!bValue);
            setButton5BadgeState(!bValue);
            
            payForSnackAction.setSnackType(ESnackTypes.E_MARS);
            insertedCoinAction.setSnackType(ESnackTypes.E_MARS);
            jSlider2.setValue(0);
        }
        
        ShowSnackMachineInFront(bValue);
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    /**
     * Selects Coca Cola snack, sets up the state of the main view
     * and sets the coin type for some controllers.
     * @param evt
     */
    private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton3ActionPerformed
        boolean bValue = jToggleButton3.isSelected();
        
        setButton3BadgeState(bValue);
        
        if (true == bValue){
            ImageIcon icon = new ImageIcon(getClass().getResource(Defines.RESOURCES_PATH + "cocaCola_big.jpg"));
            jLabel3.setIcon(icon);
            
            setButton1BadgeState(!bValue);
            setButton2BadgeState(!bValue);
            setButton4BadgeState(!bValue);
            setButton5BadgeState(!bValue);
            
            payForSnackAction.setSnackType(ESnackTypes.E_COCA_COLA);
            insertedCoinAction.setSnackType(ESnackTypes.E_COCA_COLA);
            jSlider2.setValue(0);
        }
        ShowSnackMachineInFront(bValue);
    }//GEN-LAST:event_jToggleButton3ActionPerformed

    /**
     * Selects Eugenia snack, sets up the state of the main view
     * and sets the coin type for some controllers.
     * @param evt
     */
    private void jToggleButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton4ActionPerformed
        boolean bValue = jToggleButton4.isSelected();
        
        setButton4BadgeState(bValue);
        
        if (true == bValue){
            ImageIcon icon = new ImageIcon(getClass().getResource(Defines.RESOURCES_PATH + "eugenia_big.jpg"));
            jLabel3.setIcon(icon);
            
            setButton1BadgeState(!bValue);
            setButton2BadgeState(!bValue);
            setButton3BadgeState(!bValue);
            setButton5BadgeState(!bValue);
            
            payForSnackAction.setSnackType(ESnackTypes.E_EUGENIA);
            insertedCoinAction.setSnackType(ESnackTypes.E_EUGENIA);
            jSlider2.setValue(0);
        }
        ShowSnackMachineInFront(bValue);
    }//GEN-LAST:event_jToggleButton4ActionPerformed

     /**
     * Selects Water, sets up the state of the main view
     * and sets the coin type for some controllers.
     * @param evt
     */
    private void jToggleButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton5ActionPerformed
        boolean bValue = jToggleButton5.isSelected();
        
        setButton5BadgeState(bValue);
        
        if (true == bValue){
            ImageIcon icon = new ImageIcon(getClass().getResource(Defines.RESOURCES_PATH + "water_big.jpg"));
            jLabel3.setIcon(icon);
            
            setButton1BadgeState(!bValue);
            setButton2BadgeState(!bValue);
            setButton3BadgeState(!bValue);
            setButton4BadgeState(!bValue);
            
            payForSnackAction.setSnackType(ESnackTypes.E_WATER);
            insertedCoinAction.setSnackType(ESnackTypes.E_WATER);
            jSlider2.setValue(0);
        }
        ShowSnackMachineInFront(bValue);
    }//GEN-LAST:event_jToggleButton5ActionPerformed

     /**
     * Selects the coin type in the slider, sets up a image according to the chosen coin 
     * and sets the coin type for InsertedCoinAction controller.
     * @param evt
     */
    private void jSlider1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider1StateChanged
        try{
            insertedCoinAction.setCoinType(transformIntToCoinType(jSlider1.getValue()));
        }catch(Exception ex){
            //do nothing
        }
        
        switch(jSlider1.getValue()){
            case 0:{
                ImageIcon icon = new ImageIcon(getClass().getResource(Defines.RESOURCES_PATH + "coin_0.05.png"));
                jLabel2.setIcon(icon);
                break;
            }
            case 1:{
                ImageIcon icon = new ImageIcon(getClass().getResource(Defines.RESOURCES_PATH + "coin_0.10.png"));
                jLabel2.setIcon(icon);
                break;
            }
            case 2:{
                ImageIcon icon = new ImageIcon(getClass().getResource(Defines.RESOURCES_PATH + "coin_0.20.png"));
                jLabel2.setIcon(icon);
                break;
            }
            case 3:{
                ImageIcon icon = new ImageIcon(getClass().getResource(Defines.RESOURCES_PATH + "coin_0.50.png"));
                jLabel2.setIcon(icon);
                break;
            }
            case 4:{
                ImageIcon icon = new ImageIcon(getClass().getResource(Defines.RESOURCES_PATH + "coin_1.00.png"));
                jLabel2.setIcon(icon);
                break;
            }
            default: break;
        }

    }//GEN-LAST:event_jSlider1StateChanged

    
    /**
     * Changes the amount for selected snack in the slider, sets up the value in a label
     * according to the chosen amount and updates the amount for some controllers.
     * @param evt
     */
    private void jSlider2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider2StateChanged
        payForSnackAction.setSelectedQuantity(jSlider2.getValue() + 1);
        insertedCoinAction.setSelectedQuantity(jSlider2.getValue() + 1);
        if (0 == jSlider2.getValue()){
            jLabel18.setText(Integer.toString(jSlider2.getValue() + 1) + " pc");
        }else{
            jLabel18.setText(Integer.toString(jSlider2.getValue() + 1) + " pcs");
        }
    }//GEN-LAST:event_jSlider2StateChanged

     /**
     * Works as a button for the sign in. Resets the state of the admin page and sets it as visible
     * @param evt
     */
    private void jLabel21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseClicked
        adminJDialog.resetToLogin();
        adminJDialog.setVisible(true);
    }//GEN-LAST:event_jLabel21MouseClicked

     /**
     * Sets the state of Crisps badge
     * @param bValue
     */
    private void setButton1BadgeState(boolean bValue) {                                               
        jLabel5.setVisible(bValue);
        jLabel10.setVisible(bValue);
        jToggleButton1.setSelected(bValue);
    }
    
    /**
     * Sets the state of Mars Bar badge
     * @param bValue
     */
    private void setButton2BadgeState(boolean bValue) {                                               
        jLabel6.setVisible(bValue);
        jLabel11.setVisible(bValue);
        jToggleButton2.setSelected(bValue);
    }
    
    /**
     * Sets the state of Coca Cola badge
     * @param bValue
     */
    private void setButton3BadgeState(boolean bValue) {                                               
        jLabel7.setVisible(bValue);
        jLabel12.setVisible(bValue);
        jToggleButton3.setSelected(bValue);
    }
    
    /**
     * Sets the state of Eugenia badge
     * @param bValue
     */
    private void setButton4BadgeState(boolean bValue) {                                               
        jLabel8.setVisible(bValue);
        jLabel13.setVisible(bValue);
        jToggleButton4.setSelected(bValue);
    } 
    
    /**
     * Sets the state of Water badge
     * @param bValue
     */
    private void setButton5BadgeState(boolean bValue) {                                               
        jLabel9.setVisible(bValue);
        jLabel14.setVisible(bValue);
        jToggleButton5.setSelected(bValue);
    } 
    
     /**
     * Sets the state of the snack machine as visible or invisible
     * @param bValue
     */
    private void ShowSnackMachineInFront(boolean bValue){
        jLabel17.setVisible(!bValue);//description title label
        jLabel20.setVisible(!bValue);//description info label
        
        jLabel15.setVisible(bValue);// label  
        jLabel16.setVisible(bValue);// label       
        jLabel18.setVisible(bValue);// label       
        jLabel19.setVisible(bValue);// label       
        jLabel2.setVisible(bValue);// label
        jLabel3.setVisible(bValue);//image label
        jLabel4.setVisible(bValue);//main label
        
        jSlider1.setVisible(bValue);//coin slider
        jSlider2.setVisible(bValue);//pieces slider
        
        jButton1.setVisible(bValue);//insert button
        jButton3.setVisible(bValue);//pay button
        jButton4.setVisible(bValue);//cash in button
        

    }
    
     /**
     * Gets the type of a coin by his referenced integer value
     * @param nValue
     */
    private ECoinTypes transformIntToCoinType(int nValue){
        
        switch(nValue){
            case 0:
                return ECoinTypes.E_0_05;
            case 1:
                return ECoinTypes.E_0_1;
            case 2:
                return ECoinTypes.E_0_2;
            case 3:
                return ECoinTypes.E_0_5;
            case 4:
                return ECoinTypes.E_1_0;
            default:{
                throw new ExceptionInInitializerError();
            }
        }
    }
    
    /**
     * Catches property change event
     * @param pce
     */
    @Override
    public void propertyChange(PropertyChangeEvent pce) {
        switch (pce.getPropertyName()) {
            case Defines.EVENT_INSERTED_COIN:
                jLabel16.setText(pce.getNewValue().toString());
                repaint();
                break;
            case Defines.EVENT_PAY_FOR_SNACK:
                jLabel16.setText("0.0");
                jLabel15.setText(Double.valueOf(Defines.DECIMAL_FORMAT
                    .format(pce.getNewValue())).toString());
                jSlider2.setValue(0);
                repaint();
                break;
            case Defines.EVENT_CASH_IN:
                jLabel15.setText("0.0");
                repaint();
                break;
            case Defines.EVENT_CRISPS_Q:
                jLabel10.setText(pce.getNewValue().toString());
                jSlider2.setMaximum((int)pce.getNewValue() - 1);
                break;
            case Defines.EVENT_MARS_Q:
                jLabel11.setText(pce.getNewValue().toString());
                jSlider2.setMaximum((int)pce.getNewValue() - 1);
                break;
            case Defines.EVENT_COKE_Q:
                jLabel12.setText(pce.getNewValue().toString());
                jSlider2.setMaximum((int)pce.getNewValue() - 1);
                break;
            case Defines.EVENT_EUGENIA_Q:
                jLabel13.setText(pce.getNewValue().toString());
                jSlider2.setMaximum((int)pce.getNewValue() - 1);
                break;
            case Defines.EVENT_WATER_Q:
                jLabel14.setText(pce.getNewValue().toString());
                jSlider2.setMaximum((int)pce.getNewValue() - 1);
                break;
            case Defines.EVENT_SYNC_UP:
                SyncUpData data;
                data = (SyncUpData)pce.getNewValue();
                
                jLabel16.setText(data.dInsertedCoins.toString());
                jLabel15.setText(Double.valueOf(Defines.DECIMAL_FORMAT
                    .format(data.dCashIn)).toString());
                jLabel19.setText("£ " + Double.valueOf(Defines.DECIMAL_FORMAT
                    .format(data.dPrice)).toString());
                
                switch(data.type){
                    case E_CRISPS:
                        jLabel10.setText(data.nQuantity.toString());
                        break;
                    case E_MARS:
                        jLabel11.setText(data.nQuantity.toString());
                        break;
                    case E_COCA_COLA:
                        jLabel12.setText(data.nQuantity.toString());
                        break;
                    case E_EUGENIA:
                        jLabel13.setText(data.nQuantity.toString());
                        break;
                    case E_WATER:
                        jLabel14.setText(data.nQuantity.toString());
                        break;
                    default:
                        throw new AssertionError(data.type.name());
                        }
                jSlider2.setMaximum(data.nQuantity - 1);
                break;
            case Defines.EVENT_ERROR :
                JOptionPane.showMessageDialog(new JFrame(), pce.getNewValue().toString(),
                        "Dialog", JOptionPane.ERROR_MESSAGE);
                break;
            default:
                break;
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JSlider jSlider2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton4;
    private javax.swing.JToggleButton jToggleButton5;
    // End of variables declaration//GEN-END:variables

}
